[package]
name = "scaffold-stylus-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = "0.4.1"
wasm-bindgen = "0.2"
primitive-types = { version = "0.12", default-features = false }
alloy-primitives = "0.3.1"
alloy-sol-types = "0.3.1"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ruint = "1.9.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.9"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "deploy"
path = "scripts/deploy.rs"